#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

echo -e "${YELLOW}Starting testing...${NC}"

# Run pylint
echo -e "${YELLOW}Running pylint...${NC}"
pylint **/*.py
if [ $? -ne 0 ]; then
    echo -e "${RED}Pylint failed. Exiting...${NC}"
    exit 1
else
    echo -e "${GREEN}Pylint passed!${NC}"
fi
