#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

echo -e " "
echo -e "${YELLOW}Building project...${NC}"
echo -e " "

# Update Django Environment
bash ~/bin/django/update_env
if [ $? -ne 0 ]; then
    handle_error "Django Environment Update failed. Exiting..."
fi

# Build Docker image
bash ~/bin/sdlc/build
if [ $? -ne 0 ]; then
    handle_error "Build script failed. Exiting..."
fi

# Push Docker images to Docker Hub
echo -e "${YELLOW}Pushing Docker images to Docker Hub...${NC}"

# Push Database Image
echo -e "${YELLOW}Pushing Database image...${NC}"
docker compose push db
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker database image failed to push. Exiting...${NC}"
    echo -e " "
    exit 1
fi

# Push Web Image
echo -e "${YELLOW}Pushing Database image...${NC}"
docker compose push web
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker database image failed to push. Exiting...${NC}"
    echo -e " "
    exit 1
fi

echo -e "${GREEN}Docker images successfully pushed to Docker Hub!${NC}"
echo -e "${GREEN}Deployment script completed successfully!${NC}"
echo -e " "
