#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Stop any running containers using port 8000 (optional)
echo -e " "
echo -e "${YELLOW}Stopping containers using Port 8000...${NC}"
echo -e " "

# Capture the output of the docker stop command
stopped_containers=$(docker ps -q --filter "ancestor=web")

if [ -n "$stopped_containers" ]; then
    docker stop $stopped_containers
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to stop running containers using port 8000. Exiting...${NC}"
        exit 1
    else
        echo -e "${GREEN}Successfully stopped containers using port 8000.${NC}"
    fi
else
    echo -e "${GREEN}No containers found using port 8000. Skipping stop step.${NC}"
fi

# Start process
echo -e " "
echo -e "${YELLOW}Building project...${NC}"
echo -e " "

# Update Django Environment
bash ~/bin/django/update_env
if [ $? -ne 0 ]; then
    handle_error "Django Environment Update failed. Exiting..."
fi

# Start Docker Build process
echo -e "${YELLOW}Starting Docker Build Prcess...${NC}"
bash ~/bin/sdlc/build
if [ $? -ne 0 ]; then
    handle_error "Build script failed. Exiting..."
fi

# Build Web Image
echo -e "${YELLOW}Building Web image...${NC}"
docker compose build web
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker web image build failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

# Push Docker images to Docker Hub
echo -e "${YELLOW}Pushing Docker images to Docker Hub...${NC}"

# Push Database Image
echo -e "${YELLOW}Pushing Database image...${NC}"
docker compose push db
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker database image failed to push. Exiting...${NC}"
    echo -e " "
    exit 1
fi

# Push Web Image
echo -e "${YELLOW}Pushing Database image...${NC}"
docker compose push web
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker database image failed to push. Exiting...${NC}"
    echo -e " "
    exit 1
fi

echo -e "${GREEN}Docker images successfully pushed to Docker Hub!${NC}"
echo -e "${GREEN}Deployment script completed successfully!${NC}"
echo -e " "
