#!/bin/bash

# Set Colors
source ~/bin/colors

# Define cleanup function
cleanup() {
    echo -e " "
    echo -e "${YELLOW}Stopping & Clearing Docker containers...${NC}"
    docker compose down
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to stop Docker containers. Please check manually.${NC}"
        echo -e " "
    else
        echo -e "${GREEN}Docker containers stopped successfully.${NC}"
        echo -e " "
    fi

    echo -e " "
    echo -e "${YELLOW}Pruning unused Docker images...${NC}"
    docker image prune -f
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to prune Docker images. Please check manually.${NC}"
        echo -e " "
    else
        echo -e "${GREEN}Docker images pruned successfully.${NC}"
        echo -e " "
    fi
}

# Trap EXIT signal to run cleanup
trap cleanup EXIT

# Stop any running containers using port 8000 (optional)
echo -e " "
echo -e "${YELLOW}Stopping containers using Port 8000...${NC}"
echo -e " "

stopped_containers=$(docker ps -q --filter "ancestor=web")

if [ -n "$stopped_containers" ]; then
    docker stop $stopped_containers
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to stop running containers using port 8000. Exiting...${NC}"
        echo -e " "
        exit 1
    else
        echo -e "${GREEN}Successfully stopped containers using port 8000.${NC}"
        echo -e " "
    fi
else
    echo -e "${GREEN}No containers found using port 8000. Skipping stop step.${NC}"
    echo -e " "
fi

# Run GitHub Actions simulation
echo -e "${YELLOW}Running GitHub Actions simulation using github_actions service...${NC}"
docker compose up github_actions --build
if [ $? -ne 0 ]; then
    echo -e "${RED}GitHub Actions simulation failed. Exiting...${NC}"
    exit 1
fi

echo -e "${GREEN}GitHub Actions simulation completed successfully!${NC}"
