#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Define cleanup function
cleanup() {
    echo -e " "
    echo -e "${YELLOW}Stopping & Clearing Docker containers...${NC}"
    docker compose down
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to stop Docker containers. Please check manually.${NC}"
        echo -e " "
    else
        echo -e "${GREEN}Docker containers stopped successfully.${NC}"
        echo -e " "
    fi

    echo -e " "
    echo -e "${YELLOW}Stopping & Pruning Docker images...${NC}"
    docker image prune -a
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to prune Docker images. Please check manually.${NC}"
        echo -e " "
    else
        echo -e "${GREEN}Docker images pruned successfully.${NC}"
        echo -e " "
    fi
}

# Trap EXIT signal to run cleanup
trap cleanup EXIT

# Stop any running containers using port 8000 (optional)
echo -e " "
echo -e "${YELLOW}Stopping containers using Port 8000...${NC}"
echo -e " "

# Capture the output of the docker stop command
stopped_containers=$(docker ps -q --filter "ancestor=web")

if [ -n "$stopped_containers" ]; then
    docker stop $stopped_containers
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to stop running containers using port 8000. Exiting...${NC}"
        echo -e " "
        exit 1
    else
        echo -e "${GREEN}Successfully stopped containers using port 8000.${NC}"
        echo -e " "
    fi
else
    echo -e "${GREEN}No containers found using port 8000. Skipping stop step.${NC}"
    echo -e " "
fi

# Start Process
echo -e " "
echo -e "${YELLOW}Building project...${NC}"
echo -e " "

# Update Django Environment
bash ~/bin/django/update_env
if [ $? -ne 0 ]; then
    handle_error "Django Environment Update failed. Exiting..."
fi

# Start Docker Build process
echo -e "${YELLOW}Starting Docker Build Prcess...${NC}"
bash ~/bin/sdlc/auth
if [ $? -ne 0 ]; then
    handle_error "Build script failed. Exiting..."
fi

# Build Local Web Image
echo -e "${YELLOW}Building Local Web image...${NC}"
docker compose build web
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker web image build failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

# Run Docker image Locally
echo -e "${YELLOW}Running Docker image Locally...${NC}"
docker compose up -d web
if [ $? -ne 0 ]; then
    echo -e "${RED}Creating Docker container failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

echo -e "${GREEN}Docker container created successfully!${NC}"
echo -e " "