#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Set Environmental Variables
bash ~/bin/sdlc/set_envars

echo -e " "
echo -e "${YELLOW}Building project...${NC}"
echo -e " "

# Update Django Environment
bash ~/bin/django/update_env
if [ $? -ne 0 ]; then
    handle_error "Django Environment Update failed. Exiting..."
fi

# Build Docker image
bash ~/bin/sdlc/build
if [ $? -ne 0 ]; then
    handle_error "Build script failed. Exiting..."
fi

# Run Docker image Locally
echo -e "${YELLOW}Running Docker image Locally...${NC}"
docker compose up web --remove-orphans 
if [ $? -ne 0 ]; then
    echo -e "${RED}Creating Docker container failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

echo -e "${GREEN}Docker container created successfully!${NC}"
echo -e " "