#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Start Docker Build process
bash ~/bin/sdlc/build
if [ $? -ne 0 ]; then
    handle_error "Build script failed. Exiting..."
fi

# Build CI/CD Image
echo -e "${YELLOW}Building CI/CD image...${NC}"
docker compose build check_code
if [ $? -ne 0 ]; then
    echo -e "${RED}Docker CI/CD image build failed. Exiting...${NC}"
    echo -e " "
    exit 1
fi

# Check if check_code executable exists and is executable
if [ ! -x "${PWD}/sdlc/check_code" ]; then
  echo -e "${RED}Error: check_code executable not found or not executable in ${PWD}/sdlc.${NC}"
  exit 1
fi

# Run check_code
docker compose run check_code

# Check if check_code ran successfully
if [ $? -ne 0 ]; then
  echo -e "${RED}Error: check_code failed.${NC}"
  exit 1
fi

echo -e " "
echo -e "${GREEN}CICD Test successfully complete!${NC}"
echo -e " "