#!/bin/bash

# Set Colors and handle errors
source ~/bin/colors

# Make migrations
echo -e "${YELLOW}Making migrations...${NC}"
migration_output=$(python app/manage.py makemigrations 2>&1)

# Check if the command was successful
if [ $? -ne 0 ]; then
    echo -e "${RED}Migrations failed:${NC}\n$migration_output"
    handle_error "Migrations failed. Exiting..."
else
    echo -e "${GREEN}Migrations completed successfully.${NC}"
fi

# Migrate changes as needed
if echo "$migration_output" | grep -q "No changes detected"; then
    echo -e "${YELLOW}No changes detected in migrations.${NC}"
    echo -e " "
else
    # Apply migrations
    echo -e "${YELLOW}Applying migrations...${NC}"
    python app/manage.py migrate
    if [ $? -ne 0 ]; then
        handle_error "Migration application failed. Exiting..."
    else
        echo -e "${GREEN}Migrations applied successfully!${NC}"
        echo -e " "
    fi
fi